### ISSUE TITLE
Worker testing stage runs in incorrect directory

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/SPEED#13]
### Summary
When the target repository is cloned onto the local machine while the worker is executing, the repository is cloned into a randomly generated temporary directory. However, the JVM's working directory is the same directory as the location of the worker JAR, which caused issues with executing the build commands and unit tests of the repository. Initial research into this problem showed JVM's working directory cannot be changed mid-execution. This problem has been fixed for the build stage by setting the working directory of the processes spawned from the JVM but since test execution is done in the same JVM process, this remains an issue for testing. JUnit cannot find the classes in the current classpath as this "classpath" is looking at the wrong directory.

#### Start JVM in same directory as to-be-cloned repo
We can start the JVM in the same directory as where the git repo actually will be in. This requires the directory to be created before worker execution. We will also need to tinker with the clone stage already in place in the worker. 
CC @jakejack13 

Pros
- Easy to implement (barring issues with git)
Cons
- Directory can no longer be a randomly generated temp dir unless a script is run before worker execution to set it up
- May make local (non-Dockerized) testing difficult as Dockerfile or script will need to be run before executing Java

#### Modify JUnit runner calls to set classpath
We can modify the discovery phase of the JUnit runner to modify the classpath to the correct directory. This requires modifications to API calls to the JUNit execution environment. 
CC @owenxr 

Pros
- Requires little modification to overall workflow
- Easier to run local deployments
Cons
- Not known if it's possible (requires spiking)

#### Separate out test executor as a separate Java process
We can separate out the test executor as a separate Java process, allowing us to set the working directory and classpath correctly. This requires separating out the testing stage into a separate Java project, as well as modifying the build system to add in this dependency (Gradle project and Dockerfile).
CC @MitchellGray100 

Pros
- Allows complete control over change of working directory without having to change clone and build stages

Cons
- Requires complete overhaul of testing stage into a separate Java project
- Requires modifications of build system via Gradle and Docker
- Separation of process makes worker code and execution more complex and prone to bugs and failure

**Comment by owenxr** [comment]
Something else we can look into is instead building the jar file using that to load all necessary classes and dependencies (assuming they are within the jar).
