### ISSUE TITLE
Potential Security Vulnerability

### ISSUE THREAD

**Issue by owenxr** [jakejack13/SPEED#139]
`docker_runner.py` in `first` currently relies on using subprocess to run a docker command to start the leader. This is technically an issue because the inputs are not cleaned and have the potential to cause subprocess to run malicious commands. 

Potential Alternatives:
- Security Layer to clean requests
- Move away from subprocess and use a docker library/package to start containers

_Originally posted by @owenxr in https://github.com/jakejack13/SPEED/pull/72#discussion_r1564854151_

**Comment by jakejack13** [comment]
Will be fixed with Kubernetes port
