### ISSUE TITLE
[Tester] Create More Intensive Source Code And Accompanying Tests

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/SPEED#27]
### Summary
Create code that will add more computational strain while running the test method. In addition to creating a range of code and tests. Refactoring should be done so that the test package is clean and readable. 

### Tests should be:
- More computational expensive 
- Refactored so that the test package is readable and clean.

**Comment by owenxr** [comment]
Added Preliminary Red Black Tree implementation for Testing
